name: Build novus integration project

on:
  workflow_call:
  push:
    branches: [novus-integration]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Create folder for ProductFinder.Core
        run: mkdir ProductFinder.Core
      - name: Download ProductFinder.Core
        uses: actions/download-artifact@v2
        with:
          name: core-bin
          path: ./ProductFinder.Core
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore --output novus-integration-release
      - name: Test
        run: dotnet test --no-restore --no-restore --verbosity minimal
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: core-bin
          path: ./novus-integration-release/*.dll
          retention-days: 1
