name: Build client-app
on:
    workflow_call:
jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: client-app

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # caching node_modules
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install Dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: |
                  npm ci
            - name: Build
              run: |
                  npm run build -coniguration=production
            - name: Lint
              run: |
                  npm run lint
            - name: Test
              run: |
                  npm run test

            - name: publish artifacts
              uses: actions/upload-artifact@v2
              with:
                name: client-app
                path: ./dist/client-app
                retention-days: 1

