name: Check core projects

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:
    uses: lsv-sergio/ProductFinder/.github/workflows/build-core.yml@core

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: dotnet test --no-restore --verbosity normal
