name: Check core projects

on:
  push:
    branches: [ core ]
  pull_request:
    branches: [ core ]

jobs:
  build:
    uses: lsv-sergio/ProductFinder/.github/workflows/build-core.yml@core

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: core-bin
      - name: Test
        run: ls .
#        run: dotnet test --no-restore --verbosity normal
